name: newton_breakout_revival
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.2
  flame: ^1.9.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: null
  flame_audio: ^2.1.1
  provider:
  lottie: ^2.6.0
  firebase_core: ^2.17.0
  http:
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/audio/

  fonts:
    - family: Game
      fonts:
        - asset: fonts/Game-Regular.ttf
    - family: Minecraft
      fonts:
        - asset: fonts/Minecraft-Regular1.otf
